export const awsRegions = [
    { label: "us-east-1", value: "us-east-1" }, // US East (Northern Virginia)
    { label: "us-west-2", value: "us-west-2" }, // US West (Oregon)
    { label: "us-east-2", value: "us-east-2" }, // US East (Ohio)
    { label: "us-west-1", value: "us-west-1" }, // US West (Northern California)
    { label: "ca-central-1", value: "ca-central-1" }, // Canada (Central)
    { label: "ca-west-1", value: "ca-west-1" }, // Canada West (Calgary)
    { label: "gov-west-1", value: "gov-west-1" }, // GovCloud (US-West)
    { label: "gov-east-1", value: "gov-east-1" }, // GovCloud (US-East)
    { label: "ap-southeast-1", value: "ap-southeast-1" }, // Asia Pacific (Singapore)
    { label: "ap-southeast-2", value: "ap-southeast-2" }, // Asia Pacific (Sydney)
    { label: "ap-northeast-1", value: "ap-northeast-1" }, // Asia Pacific (Tokyo)
    { label: "eu-central-1", value: "eu-central-1" }, // Europe (Frankfurt)
    { label: "eu-west-1", value: "eu-west-1" }, // Europe (Ireland)
    { label: "ap-northeast-2", value: "ap-northeast-2" }, // Asia Pacific (Seoul)
    { label: "ap-south-1", value: "ap-south-1" }, // Asia Pacific (Mumbai)
    { label: "ap-east-1", value: "ap-east-1" }, // Asia Pacific (Hong Kong)
    { label: "eu-west-2", value: "eu-west-2" }, // Europe (London)
    { label: "eu-west-3", value: "eu-west-3" }, // Europe (Paris)
    { label: "eu-north-1", value: "eu-north-1" }, // Europe (Stockholm)
    { label: "me-south-1", value: "me-south-1" }, // Middle East (Bahrain)
    { label: "sa-east-1", value: "sa-east-1" }, // South America (Sao Paulo)
    { label: "af-south-1", value: "af-south-1" }, // Africa (Cape Town)
    { label: "eu-south-1", value: "eu-south-1" },
];